In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# To find maximum value from an array.
# np.max()
	
arr1.max()

np.int64(9)

In [6]:
arr1.max(axis = 0) # return max value from each column

array([7, 8, 9])

In [7]:
arr1.max(axis = 1) # return max value from each row

array([3, 6, 9])

np.argmax()

In [8]:
arr1.argmax() # return index of max value of an array

np.int64(8)

In [9]:
# np.min()

# To find minimum value from an array.
arr1.min()

np.int64(1)

In [10]:
arr1.min(axis = 0) # return min value from each column

array([1, 2, 3])

In [11]:
#np.argmin()

arr1.argmin() # return index of min value of an array

np.int64(0)

np.sum()

Return sumation of NuPy array.

In [12]:
np.sum(arr1)

np.int64(45)

In [13]:
np.sum(arr1, axis = 0) # return sum of each column

array([12, 15, 18])

In [14]:
np.sum(arr1, axis = 1) # return sum of each row

array([ 6, 15, 24])

In [15]:
# np.mean()

# Return mean of NumPy array.
np.mean(arr1)

np.float64(5.0)

In [16]:
#np.sqrt()
#Return square root of each element of NumPy array.

np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [18]:
#np.std()
#Return standerd division of Numpy array.

np.std(arr1)

np.float64(2.581988897471611)

In [19]:
#no.exp()
#Return exponential value of each element of the NumPy array.

np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [20]:
#no.log()
#Return natural log of each element of NumPy array.

np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [21]:
#np.log10()
#Return log to the base 10 value of each element of NumPy array.

np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])