In [1]:
import numpy as np # import numpy package
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array

[1 2 3 4]


In [2]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 1D array
print(two_d_array) #printing 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
type(one_d_array) # give the type of data present in one_d_array variable

numpy.ndarray

In [4]:
one_d_array.ndim # find the dimension of one_d_array

1

In [5]:
one_d_array.size #The size attribute help to know, how many items present in a ndarray.

4

In [6]:
two_d_array.shape # The shape attribute help to know the shape of NumPy ndarray.

(3, 3)

In [7]:
one_d_array.dtype # The dtype attribute help to know the data type of ndarray.

dtype('int64')