In [2]:
import numpy as np

In [3]:
# Creating two arrays using np.arange() function and reshape it in 2D using np.reshape() function.
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
 
# print arr1 and arr2
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Addition of Two Numpy Array

In [4]:
# Using + Operator
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
# using np.add() function
	
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Subtraction of Two NumPy Array

In [6]:
# using – Operator

arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
# Using np.subtract() function

np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Division of Two NumPy Array

In [8]:
# using – Operator

arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Using np.divide() function

np.divide(arr1, arr2)


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Multiplication of Two NumPy Array

In [10]:
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

Matrix Product of Two NumPy Array (matrix)

In [12]:
#using @ Operator

arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [13]:
#Using np.dot() function

arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])