In [1]:
import numpy as np
np.ones((3,3), dtype = int) # Ones metrics use NumPy ones() function.

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [2]:
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
np.empty((2,4)) # 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
arr = np.arange(1,13) # Create NumPy 1D array using arange() function
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
arr_reshape = np.reshape(arr, (3,4)) # Convert 1D array to multidimensional array using reshape() function
print(arr_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
arr_reshape.flatten() # To convert multidimensional array into 1D use ravel() or flatten() function.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])