In [1]:
import numpy as np # import numpy package
import random # import random module

In [2]:
#np.random.random()
#This function generates float value between 0.0 to 1.0 and returns ndarray if you will give shape.

rd_num = np.random.random(1)
rd_2D_array =  np.random.random((3,3))
print(rd_num)
print(rd_2D_array)

[0.39129509]
[[0.24096321 0.85926343 0.71350348]
 [0.49332236 0.98056933 0.87232387]
 [0.64834581 0.90764096 0.37815943]]


In [3]:
#np.random.randint()
#The random integer function generates single random integer number from given range and if the shape will give then return ndarray.

rd_no = np.random.randint(1,4)
rd_2D_arr = np.random.randint(1,4, (4,4))
rd_3D_arr = np.random.randint(1,4, (2,4,4))
 
print(rd_no)
print(rd_2D_arr)
print(rd_3D_arr)

2
[[1 1 2 2]
 [3 2 1 3]
 [2 2 3 2]
 [3 1 1 2]]
[[[2 2 3 2]
  [1 2 2 1]
  [3 1 1 1]
  [3 1 3 3]]

 [[2 3 2 2]
  [1 1 1 1]
  [1 3 1 2]
  [2 2 1 1]]]


In [4]:
#np.random.seed()
#The random module generates random number but next time you want to generate the same number then seed() will help.

np.random.seed(10)
rd_3D_arr = np.random.randint(1,4, (2,4,4))
print(rd_3D_arr)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


In [5]:
#Next time generate the same 3D array using the same seed value (10).

np.random.seed(10)
rd_3D_arr = np.random.randint(1,4, (2,4,4))
print(rd_3D_arr)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


In [6]:
#np.random.rand()
#The rand() function work like random() but it accept shape and return ndarray which contain random values between 0.0 to 1.0.

arr_2D = np.random.rand(3,3) # return  3 x 3 matrix
print(arr_2D)

[[0.13145815 0.41366737 0.77872881]
 [0.58390137 0.18263144 0.82608225]
 [0.10540183 0.28357668 0.06556327]]


In [7]:
#np.random.randn()
#The randn() function work like rand() function but it reurn samples of  standerd normalise distribution value.

arr_2D = np.random.randn(3,3)
print(arr_2D)

[[ 0.67893119 -1.91355421 -0.94245806]
 [-1.74554298 -1.02094527 -0.16206903]
 [-0.6579709   0.42211306  0.62402334]]


In [8]:
#np.random.choice()
#If you have sequence values and want to get random single value then the random choice() function is the best choice.

x = [1,2,3,4] # list
choice_from_x = np.random.choice(x) # retun random single item from sequence
print(choice_from_x )

1


In [9]:
#Let’s try to get the number of choice from sequence x using for loop.

for i in range(20):
    print(np.random.choice(x))

1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3
4
1
1
1


In [10]:
#np.random.permutation()
#If you want to generate some permutation of sequence then use random permutation() function.

x_permute = np.random.permutation(x)
print(x_permute)

[2 4 3 1]
